name: Build Typst document
on: 
  workflow_dispatch: 
  schedule:
    - cron: '0 5 * * *'

permissions:
  contents: write

jobs:
  filter:
    outputs:
      new-commits-nonzero: "git log --oneline --since '24 hours ago' | wc -l -gt 0"

  build:
    needs: [filter, new-commits-nonzero]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

     
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            __main.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "*.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: main.pdf
